name       : jabref
version    : '5.5'
release    : 4
source     :
    - https://github.com/JabRef/jabref/archive/refs/tags/v5.5.tar.gz : af0d7c5566aec94ffa8b5912c116956ccf17331e5b46bb5adbd6afeaa85ac230
license    : MIT
component  : office
summary    : Graphical Java application for managing BibTeX and BibLaTeX (.bib) databases
description: |
    Graphical Java application for managing BibTeX and BibLaTeX (.bib) databases
builddeps  :
    - gradle
    - openjdk-17
rundeps    :
    - openjdk-17
networking : yes
environment: |
    export JAVA_HOME=/usr/lib64/openjdk-17
    export PATH=$JAVA_HOME/bin:$PATH

    export GRADLE_USER_HOME=$workdir
build      : |
    gradle \
      --no-daemon \
      -PprojVersionInfo=$version \
      -PprojVersion=$version \
      assemble
install    : |
    install -D -m 00755 $pkgfiles/jabref.sh $installdir/usr/bin/jabref
    install -D -m 00644 $pkgfiles/jabref.desktop -t $installdir/usr/share/applications
    install -D -m 00644 build/resources/main/icons/jabref.svg -t $installdir/usr/share/icons/hicolor/scalable/apps

    install -d -m 00644 $installdir/usr/share/jabref
    tar -xf build/distributions/JabRef-*.tar --strip-components=1 -C $installdir/usr/share/jabref
