name       : jabref
version    : 3.8.2
release    : 1
source     :
    - https://github.com/JabRef/jabref/archive/v3.8.2.tar.gz : 35bc404781f5a3fab0a7d9a96b6139352e78c39133490a4d0369c99d55e74d94
license    : MIT
component  : office
summary    : Graphical Java application for managing BibTeX and BibLaTeX (.bib) databases
description: |
    Graphical Java application for managing BibTeX and BibLaTeX (.bib) databases
builddeps  :
    - gradle
    - openjdk-8-devel
rundeps    :
    - openjdk-8
networking : yes
build      : |
    export GRADLE_USER_HOME=/home/build/YPKG/root/jabref
    gradle --no-daemon releaseJar
install    : |
    install -D -m 00644 $pkgfiles/jabref.desktop $installdir/usr/share/applications/jabref.desktop
    install -D -m 00644 build/resources/main/images/icons/JabRef-icon.svg $installdir/usr/share/icons/hicolor/scalable/apps/jabref.svg
    install -D -m 00644 build/releases/JabRef-$version.jar $installdir/usr/share/jabref/jabref.jar

