name       : jabref
version    : '4.2'
release    : 2
source     :
    - https://github.com/JabRef/jabref/archive/v4.2.tar.gz : 1eb915068316a8b67b8a10a44a619abe505d4756efdbf2683ed1fd343064fc7e
license    : MIT
component  : office
summary    : Graphical Java application for managing BibTeX and BibLaTeX (.bib) databases
description: |
    Graphical Java application for managing BibTeX and BibLaTeX (.bib) databases
builddeps  :
    - gradle
    - openjfx-8
rundeps    :
    - openjfx-8
networking : yes
build      : |
    export GRADLE_USER_HOME=/home/build/YPKG/root/jabref
    ./gradlew --no-daemon releaseJar
install    : |
    install -D -m 00644 $pkgfiles/jabref.desktop $installdir/usr/share/applications/jabref.desktop
    install -D -m 00644 build/resources/main/icons/jabref.svg $installdir/usr/share/icons/hicolor/scalable/apps/jabref.svg
    install -D -m 00644 build/releases/JabRef-$version.jar $installdir/usr/share/jabref/jabref.jar

